### ISSUE TITLE
关于war包

### ISSUE THREAD

**Issue by ljfyuyu** [horacework/Parking-Services-based-on-Spring-New#1]
您好，请问您提到的war包，在哪里呢?  >>>>>>”2016.06.01 答辩完成。目标基本完成。项目不再更新了。Tomcat占用资源太厉害了，云主机上的本项目服务器已撤掉。（如需要，请下载target文件夹下的war包进行部署）“

**Comment by horacework** [comment]
不好意思！你不提我还没注意，.gitignore把target文件夹给忽略掉了。。。要不你用代码导出一个war包出来？年代久远，电脑换了几台，我未必能找到之前的war包。

**Comment by ljfyuyu** [comment]
好的，谢谢你啦。

**Comment by horacework** [comment]
找到之前那份war包了，留下邮箱我发给你。

**Comment by ljfyuyu** [comment]
1244684331@qq.com,  O(∩_∩)O谢谢哈
